### PR TITLE
Add missing help strings, add packaging

### PR DESCRIPTION
**Pull request by kensanata**
* Add missing help strings.
* Prevent exception when using the reload command first thing in a session.
* Do the [packaging stuff](https://packaging.python.org/tutorials/distributing-packages/)

To run as a developer, install an "editable" copy by running `sudo pip3 install -e .` or something like that.

### CODE REVIEW

**Comment by solderpunk** [comment]
Hey!  I appreciate you doing the boring work of setting up packaging, etc.

I hope you don't mind but I might make some changes before putting this on PyPi (especially because there are just a few more navigation related features I want to add before first release!).    I know a certain amount of overhead to work nicely with setuptools is unavoidable, but because VF-1 is so very small and simple I would love to try to keep the repo as clean as possible, without doing anything really "bad".

Mostly, I would love to avoid having to replace the single file `vf1.py` with `vf1/__init__.py` and `vf1/vf1.py` if possible.  In addition to being neater, this makes it easy to install VF-1 manually in pathological scenarios where setuptools can't be used, by just dumping the file in `~/bin/` and `chmod`ding it (and modern Gopher users are probably highly disposed to getting themselves in pathological scenarios!).

**Comment by kensanata** [comment]
Yeah, absolutely valid points! You do with it what works best. For now, you can always run vf1.py directly in addition to doing the entire thingamaging...

**Comment by kensanata** [comment]
Oh. You merged the code anyway? As for the technical benefits you asked about, I can't really tell you much.  I was shown how to do it by somebody else who rewrite my Mastodon Archive tool for **pip install** -- and that's the only real benefit, I think. I had a user download my code and then wonder why no binary or script had been installed and then I realized that end users simply expected to pip install foo and then foo would be a new command on their system.

**Comment by solderpunk** [comment]
Yeah, I wanted all the nice docstrings and handling of edge cases you put in, and I want *some* kind of `setup.py`, so it seemed simplest to just merge this and then make the changes I wanted.

And no worries about the other stuff.  I have used the `entry_points` stuff (and, earlier, the `scripts` stuff) for CLI projects before, but some of the other stuff I haven't seen.  I'll do some reading and see how much I can slim things down.

Thanks again for your help!

**Comment by kensanata** [comment]
I like to help because I like the command line browser. It's perfect at work and it's surprisingly fast to use, so I've started using it a lot more.
I'm not sure what to do with the two [additional commits](https://github.com/kensanata/VF-1/commits/master) I made. They now add two optional command line arguments to __init__.py so that, if you installed it correctly, you can now do `vf1 --bookmarks` and `vf1 --go phlogosphere.org`...

**Comment by solderpunk** [comment]
Ah, interesting.  Those seem like useful features (although I would probably prefer just `vf1 phlogosphere.org` without the `--go`.

Later tonight I'm going to push two new navigation features which, IMHO, will be the real killer features of VF-1, making it easy to do long sessions cruising through gopherspace without getting lost or wasting lots of time backing up to menus after diving deep into the first option.

**Comment by kensanata** [comment]
Looking forward to it! As for `--go` I absolutely agree with you but I was unable to teach argparse how to do it. So if you know a way to improve upon it, that would be great!

**Comment by solderpunk** [comment]
Alright, those new features are in, at least in their most basic form.

I'm out of hobby time for tonight, but tomorrow I will have a go at streamlining the package stuff and will try to get your command line options included, too.

**Pull request merged**
